# Generated by Django 2.1.2 on 2019-06-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190629_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavor',
            old_name='name',
            new_name='flavor',
        ),
    ]
